# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c45a7b62754e6ded669fad58b952de83064e3b0515d9a7f1d1332827de3fc64803b277f882f8e5a2c6eef966b3127695a0e39069812ae6e4d2ae98eef76551

test:
  secret_key_base: 7205d2b304759ec007ac06bf72e5f1bd7c134655e12c992d0b0f46996296cd1db9285ca1e99be9c1f72a6f324576b9c61bf7d2926d072bfd110e776fe0d1b190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
